### ISSUE TITLE
[RFC] Split reaction into multiple bundles

### ISSUE THREAD

**Issue by zephraph** [artsy/reaction#1685]
Reaction is a labor of love that every team touches in some way. It's growth has been both rapid and (at times) a bit chaotic. I think it's fair to say it's grown beyond it's original intent at this point. 

There are at least two major categories of things that live inside of reaction. Apps which are full experiences that are injected into force and components which are imported and injected into other projects. Consumers like volt and positron will never use the apps that are consumed by force. Breaking some of these pieces down into separate packages could mean pulling less transient dependencies into downstream packages. Another advantage would be reducing package churn on unused areas of code. For example, positron wouldn't need to upgrade reaction if the artwork app changed. Of course, nothing comes without downsides. Generally this would mean supporting a monorepo structure or some other mechanism of separation that will come with its own challenges. With the monorepo approach I'm particularly concerned about any increased difficulty with linking across projects. 

Regardless of the approach, I still think we should pursue breaking reaction down into smaller, more maintainable packages. We'll need to decide what granularity of packages makes sense too. Should every app be its own packages? Should there be a components package, or should certain component groups (like publishing) be pulled into their own package?

Thoughts or questions?

**Comment by orta** [comment]
> With the monorepo approach I'm particularly concerned about any increased difficulty with linking across projects.

This is what yarn workspaces are good at FWIW

**Comment by ashfurrow** [comment]
> we should pursue breaking reaction down into smaller, more maintainable packages

I'm a big 👍 on this, but as you point out it's easier said than done. My only concern is a combinatorial explosion of packages and an increasing amount of time spent wrangling our various packages.

One thing to keep in mind as we move forward on this is of course our [Engineering Guiding Principles](https://github.com/artsy/README/blob/master/culture/engineering-principles.md). The one that comes to mind is "incremental revolution" – our solution to splitting out Reaction should be bold, but would ideally shield most frontend engineers from dealing with additional complexity in day-to-day product work.

**Comment by williardx** [comment]
Could we just fold the Force-specific apps back into Force?

**Comment by zephraph** [comment]
> Could we just fold the Force-specific apps back into Force?

That's certainly a possibility, but that wouldn't necessarily fully eliminate the need to break down reaction. Still, I think it's a valid point and something worth considering.

**Comment by zephraph** [comment]
The more I think about it, the more I like the idea. Moving the apps into force greatly reduces the need to link. Being as that's a pretty continual source of issues that'd make development easier.

**Comment by damassi** [comment]
Any thoughts @alloy?

**Comment by alloy** [comment]
I think moving apps into Force makes sense, from a conceptual perspective at least. Personally I’m a little hesitant about developing inside Force with the overall setup being slower than working in an isolated environment, _but_ if most people work on Reaction from inside Force already anyways then that point is very moot.

@zephraph One thing to keep in mind is that _if_ we’re ever to move to a MP v2 schema setup, the individual apps would still need to have their own relay-compiler setup so they can use different schemas. That’s not a reason to not do this move now, but it _may_ be a good reason to still have a workspace setup.

**Comment by zephraph** [comment]
Would an omakase shared setup be able to help resolve that?

**Comment by damassi** [comment]
> Personally I’m a little hesitant about developing inside Force with the overall setup being slower than working in an isolated environment

I don't think this move should exclude a storybooks setup; that abstraction seems to have worked well so far!

**Comment by alloy** [comment]
@zephraph Not sure how. Can you elaborate?

**Comment by orta** [comment]
If we move the server + routing into reaction (ideally via sub-packages) then it would be pretty easy to add visual regression testing to new apps

**Comment by orta** [comment]
Re: Moving apps back to force.

I think one of the goals for reaction should be to provide a reliable dev env for working in web apps too, not just as a component library. For example, teams work entirely in Emission for months without working in Eigen because they trust that it will work the same across those two environments - for dev Emission provides a library host and provides a component library. It took a bunch of work to get that level of trust in Emission.

Ideally, that work should happen in Reaction too. Right now though, Reaction does the component library well, but doesn't provide a useful enough host. To do so has two main angles:

- Letting reaction own from routing to rendering
- Letting reaction own the entire DOM 

So, IMO, moving apps to live in force is basically giving up on having a solid reliable single place for doing your work and leaves a tonne of complexity in having to have force set up, linked and handle partial aspects of the rendering process.

Ideally all it would look like in force to use a reaction app, is to pass it a single express function and that's all the integration is (which emulates how we pass a single native screen across the Eigen/Emission gap)

**Comment by alloy** [comment]
> Ideally all it would look like in force to use a reaction app, is to pass it a single express function and that's all the integration is (which emulates how we pass a single native screen across the Eigen/Emission gap)

:ceiling-cat: Just want to note that that is what [this PR](https://github.com/artsy/reaction/pull/1524/files) was working towards (although some stitching is still necessary for things like headers or modals that still live in Force).

**Comment by orta** [comment]
Hah, I swear you and I are a semi-hivemind @alloy

**Comment by damassi** [comment]
> Emission provides a library host and provides a component library. It took a bunch of work to get that level of trust in Emission

I don't think Reaction, Emission, Force and Eigen should be compared since native is inherently more complex, is C-based, etc. The only practical similarity is React and Eigen being a host environment. However, Eigen as a development environment is much different than force as a development environment, and this needs to be fully appreciated. 

When thinking in terms of Reaction and Force and their overall infrastructural setup, things are nearly identical. Both use the same babel config, and roughly the same Webpack config. When Force boots, it iterates over files located in an assets folder and creates separate bundle for each asset. Once things are booted, compiles are cached according to asset, and compile times are between .5 to 1.5 seconds -- fast. Working inside of Force requires no special infrastructure (except for stitch) and is pretty simple. Adding things is as easy as adding a new asset file, which webpack automatically picks up. Additionally, if we wanted to detatch Force from the complete asset pipeline that runs artsy.net (to run, say, storybooks, or whatever else), we could pass an array of webpack configs into the webpack-cli from directly in force. Separate processes, without the boundaries of package management, linking, or special infrastructure.  

By moving all of this into Reaction and creating reverse-bindings between Force and Reaction via stitch, we're a) increasing our reliance on a tool that was meant to be used temporarily; and b) creating a maintenance burden for reasons that might not be necessary.

**Comment by mzikherman** [comment]
Coming at this a bit late, I'm still trying to understand the problem/issues currently facing Reaction. I totally understand that having a component lib and full(er) apps living in the same repo feels odd, but we've ironed out all those kinks as @damassi points out.

`yarn link` and the general state of front-end web development seems really...awesome these days. I'm seeing two issues mentioned in the top comment as possible problems:

- churn in client apps due to unrelated updates (with Renovate this doesn't feel like a big problem really)
- extra dependencies being pulled in (this feels more compelling- something like `moment` is depended upon by an app, and so any client using any component will have that pulled in).

However, I also thought that one goal we had was to be able to rebuild the _full_ pages in Force (including the NAV), inside of Reaction, and begin chipping away at the bundle sizes in Force.

Moving full apps from Reaction into Force feels very murky and as @orta points out I think will really increase complexity.

Now, if people are fine with components and apps living side by side, but _still_ want to explore better organization and handling of dependencies (via splitting Reaction or a different repo setup), I think that would be more worthwhile than moving apps into Force. We should be careful however, even in just splitting up in Reaction, that we're not adding a lot of complexity and intermediate states and a lot of time/effort to reach an ideal, vs the current agreeable state. Personally, Reaction doesn't at all feel big enough that it's hard to work with, whether it's storybooks, a linked state, an app component, etc.

**Comment by damassi** [comment]
Re

> I think one of the goals for reaction should be to provide a reliable dev env for working in web apps too, not just as a component library.

This is already exactly what we're doing, thanks to GraphQL and Relay's network layer. Multiple apps have been built out quite extensively in Reaction, and during the later stages tested in Force. This is how `/artist`, `/artwork`, `/order`, `/collect` and `/collections` were built. Reaction is already far past a component library, and has been so since we started using the new routing setup (which Reaction controls with the exception of some [Force tech-debt](https://github.com/artsy/force/blob/master/src/desktop/apps/artist/client.tsx#L45-L58) from when we first laid down the pattern (this code should be controlled by Found)).

Using the new Artwork page as an example, aside from triggering the login modal and mounting our router, there is a [one-line dependency from Force](https://github.com/artsy/force/blob/master/src/desktop/apps/artwork2/server.tsx#L42); Reaction is able to handle everything else. And to trigger the modal, it's `mediator.trigger('login', { ... })`. It's not a far stretch to imagine a session being updated via a mutation, in which case we can call the Login modal directly from Reaction and skip the mediator completely.

**Comment by damassi** [comment]
As an aside, we're getting pretty close to completely decoupling Palette from Reaction. What remains at this point in terms of a potential monorepo split would be:  

- v1 (legacy components): things located in [`/Components`](https://github.com/artsy/reaction/tree/master/src/Components) 
- v2 (modern design-system components): [`/Styleguide/Components`](https://github.com/artsy/reaction/tree/master/src/Styleguide/Components). These need to be moved to a `v2` folder. 
- Analytics: [`/Artsy/Analytics`](https://github.com/artsy/reaction/tree/master/src/Artsy/Analytics)
- Routing: [`/Artsy/Router`](https://github.com/artsy/reaction/tree/master/src/Artsy/Router)
- DevTools: [`/DevTools`](https://github.com/artsy/reaction/tree/master/src/DevTools)
- Apps: [`/Apps`](https://github.com/artsy/reaction/tree/master/src/Apps) (Including Publishing code)

**Comment by sweir27** [comment]
I'm not opposed to this generally! But having worked only minimally in a monorepo/etc. I'm curious if there's a way to do this in an incremental way and to evaluate whether it's what we want to be doing before we make a big change.

Some thoughts re: the discussion of moving things back into force (or in general re-thinking how we architect things): 
- Working on BNMO was (aside from building components) pretty impossible to do _just_ in storybooks. I found it always preferable to build anything with any sort of logic with reaction linked within force. Linking did work 👌 but _testing_ anything end-to-end and exercising the force-reaction interface is nearly impossible unless you do it manually. This could be solved in many ways but I do think it's worth revisiting! If it becomes much easier to test end-to-end with a full app inside reaction, that might be a reason to consider keeping things there.
- Re: @alloy's point about force being difficult to work in, I wonder if having more cooks in that kitchen could actually improve the developer experience overall (this feels like a separate problem IMO).

I know this ☝️ is a separate discussion than the original RFC, but if it informs this change in any way it seems worth mentioning!

**Comment by zephraph** [comment]
There's a lot of good discussion here, but I haven't had the time to dedicate to resolving this RFC. I'm going to close it for now, and we can re-open it once we have more time to work towards a solution.
